# Generated by Django 4.2.1 on 2023-06-01 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magasinapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='magasin',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='magasinapp.magasin'),
        ),
    ]
